name: test-on-push
on: [push]
jobs:
  test-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i
      - run: mongodb -v