name: test-on-push
on: [push]
jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i
      - run: npm run test
        env:
            NODE_ENV: "test"
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
            FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
            JIMBO_PASSWORD: ${{ secrets.JIMBO_PASSWORD }}
  deploy:
    needs: jest-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jimbo-ilegal-deli" #Must be unique in Heroku
          heroku_email: "ianapblair@gmail.com"